version: '3'
services:
  postgres_db19:
    image: postgres:14-alpine
    container_name: "postgres${PORT}"
    environment:
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: "${PSQL_DB}"
      POSTGRES_USER: "${PSQL_USER}"
    ports:
      - "100${PORT}:55${PORT}"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/usr/src/postgres"
    networks:
      - our-library-net
    command: "-p 55${PORT}"

  web19:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80${PORT}"
    container_name: "django${PORT}"
    depends_on:
      - postgres_db19
    environment:
      PSQL_DBNAME: "${PSQL_DB}"
      PSQL_USERNAME: "${PSQL_USER}"
      PSQL_PASS: "${PSQL_PASSWORD}"
      PSQL_HOST: "postgres_db${PORT}"
      PSQL_PORT: "55${PORT}"
      JWT_TOKEN_TIME: "${JWT_TOKEN_TIME}"
    volumes:
      - "${DJANGO_VOLUME_PATH}:/usr/src/django/library"
    ports:
      - "90${PORT}:80${PORT}"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge
